# Company Scraper Configuration
# ================================

# Data Sources
data_sources:
  chamber_of_commerce_url: "https://www.ufficiocamerale.it"
  search_engine_url: "https://www.startpage.com/sp/search"

# File Paths
file_paths:
  input_file: "companies_base.csv"
  chamber_urls_output: "chamber_urls.csv"
  detailed_data_output: "companies_detailed.csv"
  websites_output: "company_websites.csv"
  intelligence_output: "company_intelligence.json"
  chamber_analysis_output: "chamber_analysis.json"
  taxonomy_file: "industry_classification.json"
  unified_data_output: "unified_company_data.json"

# Scraping Settings
scraping:
  # Request delays (seconds)
  request_delay: 2
  validation_delay: 1
  company_delay: 3

  # Timeouts (seconds)
  page_timeout: 15
  selenium_timeout: 10

  # Limits
  max_candidate_websites: 8
  max_retries: 3

  # Browser settings
  headless_mode: true
  browser_width: 1920
  browser_height: 1080

# Validation Settings
validation:
  confidence_threshold: 50
  footer_score_cap: 60
  name_match_weight: 15
  max_name_match_score: 45
  tax_code_score: 25
  registration_pattern_weight: 10
  max_registration_score: 30
  business_keyword_score: 10
  contact_info_weight: 8
  max_contact_score: 20

# Search Settings
search:
  excluded_domains:
    - "startpage.com"
    - "google.com"
    - "bing.com"
    - "yahoo.com"
    - "facebook.com"
    - "linkedin.com"
    - "twitter.com"
    - "instagram.com"
    - "wikipedia.org"
    - "youtube.com"
    - "amazon.com"
    - "ebay.com"
    - "ufficiocamerale.it"
    - "registroimprese.it"
    - "infocamere.it"
    - "paginegialle.it"

# Intelligence Settings
intelligence:
  # Analysis settings
  max_pages_per_site: 5
  content_analysis_timeout: 30
  classification_confidence_threshold: 0.6

  # Ollama API settings
  ollama_endpoint: "http://ollama.lan:11434/api/generate"
  ollama_model: "gemma3:12b"
  ollama_stream: false
  ollama_temperature: 0.3
  ollama_top_p: 0.9
  ollama_timeout: 60

# Chamber Analysis Settings (Step 5)
chamber_analysis:
  max_content_length: 8000
  certification_keywords:
    - "certificazione"
    - "attestazione"
    - "qualità"
    - "quality"
    - "ambientale"
    - "environmental"
    - "sicurezza"
    - "safety"
    - "soa"
    - "iso"
    - "uni"
    - "accredia"
  business_keywords:
    - "oggetto sociale"
    - "attività"
    - "servizi"
    - "prodotti"
    - "settore"
    - "specializzazione"

# Chatbot Settings (Step 6)
chatbot:
  max_context_length: 6000
  response_max_length: 1000
  enable_dynamic_scraping: true
  conversation_history_limit: 10

  # Fallback pages to analyze when smart link discovery fails
  # The scraper first attempts intelligent link discovery from the homepage
  # using technology-specific scoring. If that fails, it falls back to these
  # predefined paths as a safety mechanism.
  pages_to_analyze:
    - "/" # Homepage (always analyzed first)
    - "/about" # English about page
    - "/chi-siamo" # Italian "who we are" page
    - "/azienda" # Italian company page
    - "/servizi" # Italian services page
    - "/products" # English products page
    - "/prodotti" # Italian products page
    - "/contatti" # Italian contact page
    - "/contact" # English contact page
